/*
 Navicat Premium Data Transfer

 Source Server         : test
 Source Server Type    : MySQL
 Source Server Version : 50721
 Source Host           : mysql.test.tuboshi.co:3306
 Source Schema         : sHouseApp_pre

 Target Server Type    : MySQL
 Target Server Version : 50721
 File Encoding         : 65001

 Date: 03/09/2018 20:47:52
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for cms_resource_definition
-- ----------------------------
DROP TABLE IF EXISTS `cms_resource_definition`;
CREATE TABLE `cms_resource_definition`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '资源名称,唯一索引',
  `definition` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '资源定义, json 格式',
  `position` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '资源定位,访问路径,唯一索引',
  `status` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '状态',
  `default_value` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '默认值',
  `value` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '值',
  `created_by` int(11) DEFAULT NULL COMMENT '创建人',
  `created_date` datetime(0) DEFAULT NULL COMMENT '创建时间',
  `last_modified_by` int(11) DEFAULT NULL COMMENT '修改人',
  `last_modified_date` datetime(0) DEFAULT NULL COMMENT '修改时间',
  `version` int(11) NOT NULL DEFAULT 0 COMMENT '版本号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `unique_index_name`(`name`) USING BTREE,
  UNIQUE INDEX `unique_index_position`(`position`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 17 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_bin ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of cms_resource_definition
-- ----------------------------
INSERT INTO `cms_resource_definition` VALUES (1, '首页导航', '{\"title\":\"首页导航\",\"type\":\"object\",\"properties\":{\"iconUrl\":{\"type\":\"img\",\"title\":\"导航图标\",\"default\":\"\"},\"name\":{\"type\":\"string\",\"title\":\"导航名\",\"description\":\"此处填写导航名称\",\"default\":\"\"},\"url\":{\"type\":\"string\",\"title\":\"导航地址\",\"description\":\"此处填写导航地址\",\"default\":\"\"},\"mUrl\":{\"type\":\"string\",\"title\":\"M站导航地址\",\"description\":\"此处填写M站导航地址\",\"default\":\"\"}}}', 'home/navigation', 'released', '', '', NULL, '2018-05-21 16:37:23', NULL, '2018-07-11 10:05:19', 8);
INSERT INTO `cms_resource_definition` VALUES (2, '首页 banner 轮播', '{\"title\":\"首页轮播图片\",\"type\":\"object\",\"properties\":{\"picUrl\":{\"type\":\"img\",\"title\":\"图片\",\"required\":true,\"default\":\"\"},\"linkUrl\":{\"type\":\"string\",\"title\":\"跳转地址\",\"default\":\"\",\"required\":true},\"mUrl\":{\"type\":\"string\",\"title\":\"M站导航地址\",\"description\":\"此处填写M站导航地址\",\"default\":\"\"},\"beginTime\":{\"type\":\"string\",\"title\":\"开始时间\",\"description\":\"此处填写{yyyy-MM-dd HH:mm:ss}格式的时间\",\"default\":\"\"},\"endTime\":{\"type\":\"string\",\"title\":\"结束时间\",\"description\":\"此处填写{yyyy-MM-dd HH:mm:ss}格式的时间\",\"default\":\"\"}}}', 'home/banner', 'released', '', '', NULL, '2018-05-21 16:37:46', NULL, '2018-07-11 10:04:48', 19);
INSERT INTO `cms_resource_definition` VALUES (3, '广告语', '{\"title\":\"广告语\",\"type\":\"object\",\"properties\":{\"slogan\":{\"type\":\"string\",\"title\":\"广告语\",\"description\":\"此处填写广告语\",\"minLength\":1,\"default\":\"看房之前， 当然要看兔博士!\"}}}', 'advertising', 'released', '', '', NULL, '2018-05-21 16:38:08', NULL, '2018-07-11 10:05:34', 5);
INSERT INTO `cms_resource_definition` VALUES (4, '新房话题资讯', '{\"title\":\"新房话题资讯\",\"type\":\"object\",\"properties\":{\"topic\":{\"type\":\"string\",\"title\":\"话题\",\"description\":\"此处填写话题\",\"minLength\":4,\"default\":\"\"},\"title\":{\"type\":\"string\",\"title\":\"标题\",\"description\":\"此处填写标题\",\"default\":\"\"},\"image\":{\"type\":\"img\",\"title\":\"封面图片\",\"description\":\"\",\"default\":\"\"},\"url\":{\"type\":\"string\",\"title\":\"跳转链接地址\",\"format\":\"url\",\"description\":\"此处填写跳转地址\",\"default\":\"rabbit://articleDetail?articleId=\"},\"mUrl\":{\"type\":\"string\",\"title\":\"M站导航地址\",\"description\":\"此处填写M站导航地址\",\"default\":\"\"},\"video\":{\"type\":\"checkbox\",\"title\":\"是否是视频\",\"format\":\"boolean\",\"default\":\"\"}}}', 'home/new_house_topic', 'released', '', '', NULL, '2018-05-21 16:48:08', NULL, '2018-07-11 10:05:59', 12);
INSERT INTO `cms_resource_definition` VALUES (5, '二手房话题资讯', '{\"title\":\"二手房话题资讯\",\"type\":\"object\",\"properties\":{\"topic\":{\"type\":\"string\",\"title\":\"话题\",\"description\":\"此处填写话题\",\"minLength\":4,\"default\":\"\"},\"title\":{\"type\":\"string\",\"title\":\"标题\",\"description\":\"此处填写标题\",\"default\":\"\"},\"image\":{\"type\":\"img\",\"title\":\"封面图片\",\"description\":\"\",\"default\":\"\"},\"url\":{\"type\":\"string\",\"title\":\"跳转链接地址\",\"format\":\"url\",\"default\":\"rabbit://articleDetail?articleId=\"},\"mUrl\":{\"type\":\"string\",\"title\":\"M站导航地址\",\"description\":\"此处填写M站导航地址\",\"default\":\"\"},\"video\":{\"type\":\"checkbox\",\"title\":\"是否是视频\",\"format\":\"boolean\",\"default\":\"\"}}}', 'home/second_hand_house_topic', 'released', '', '', NULL, '2018-05-21 16:48:57', NULL, '2018-07-11 10:07:31', 12);
INSERT INTO `cms_resource_definition` VALUES (6, '新房文章资讯', '{\"title\":\"文章资讯\",\"type\":\"object\",\"properties\":{\"title\":{\"type\":\"string\",\"title\":\"标题\",\"description\":\"此处填写你的标题\",\"minLength\":4,\"default\":\"\"},\"author\":{\"type\":\"string\",\"title\":\"文章作者\",\"default\":\"\"},\"image\":{\"type\":\"img\",\"title\":\"封面图片\",\"default\":\"\"},\"pubTime\":{\"type\":\"string\",\"title\":\"发布时间\",\"description\":\"此处填写你的发布时间格式为{MM.dd}\"},\"url\":{\"type\":\"string\",\"title\":\"跳转地址\",\"format\":\"url\",\"default\":\"rabbit://articleDetail?articleId=\"},\"mUrl\":{\"type\":\"string\",\"title\":\"M站导航地址\",\"description\":\"此处填写M站导航地址\",\"default\":\"\"}}}', 'home/new_house_article', 'released', '', '', NULL, '2018-05-21 16:52:47', NULL, '2018-07-11 10:07:49', 11);
INSERT INTO `cms_resource_definition` VALUES (7, '二手房文章资讯', '{\"title\":\"文章资讯\",\"type\":\"object\",\"properties\":{\"title\":{\"type\":\"string\",\"title\":\"标题\",\"description\":\"此处填写你的标题\",\"minLength\":4,\"default\":\"\"},\"author\":{\"type\":\"string\",\"title\":\"文章作者\",\"default\":\"\"},\"image\":{\"type\":\"img\",\"title\":\"封面图片\",\"default\":\"\"},\"pubTime\":{\"type\":\"string\",\"title\":\"发布时间\",\"description\":\"此处填写你的发布时间格式为{MM.dd}\"},\"url\":{\"type\":\"string\",\"title\":\"跳转地址\",\"format\":\"url\",\"default\":\"rabbit://articleDetail?articleId=\"},\"mUrl\":{\"type\":\"string\",\"title\":\"M站导航地址\",\"description\":\"此处填写M站导航地址\",\"default\":\"\"}}}', 'home/second_hand_house_article', 'released', '', '', NULL, '2018-05-21 16:53:18', NULL, '2018-07-11 10:07:58', 11);
INSERT INTO `cms_resource_definition` VALUES (8, '新房场景轮播图片', '{\"title\":\"新房场景轮播图片\",\"type\":\"object\",\"properties\":{\"picUrl\":{\"type\":\"img\",\"title\":\"图片\",\"required\":true,\"default\":\"\"},\"linkUrl\":{\"type\":\"string\",\"title\":\"跳转地址\",\"default\":\"\",\"required\":true},\"mUrl\":{\"type\":\"string\",\"title\":\"M站导航地址\",\"description\":\"此处填写M站导航地址\",\"default\":\"\"},\"beginTime\":{\"type\":\"string\",\"title\":\"开始时间\",\"description\":\"此处填写{yyyy-MM-dd HH:mm:ss}格式的时间\",\"default\":\"\"},\"endTime\":{\"type\":\"string\",\"title\":\"结束时间\",\"description\":\"此处填写{yyyy-MM-dd HH:mm:ss}格式的时间\",\"default\":\"\"}}}', 'new_house/banner', 'released', '', '', NULL, '2018-05-25 17:20:22', NULL, '2018-07-11 10:08:12', 5);
INSERT INTO `cms_resource_definition` VALUES (9, '二手房场景轮播图片', '{\"title\":\"二手房场景轮播图片\",\"type\":\"object\",\"properties\":{\"picUrl\":{\"type\":\"img\",\"title\":\"图片\",\"required\":true,\"default\":\"\"},\"linkUrl\":{\"type\":\"string\",\"title\":\"跳转地址\",\"default\":\"\",\"required\":true},\"mUrl\":{\"type\":\"string\",\"title\":\"M站导航地址\",\"description\":\"此处填写M站导航地址\",\"default\":\"\"},\"beginTime\":{\"type\":\"string\",\"title\":\"开始时间\",\"description\":\"此处填写{yyyy-MM-dd HH:mm:ss}格式的时间\",\"default\":\"\"},\"endTime\":{\"type\":\"string\",\"title\":\"结束时间\",\"description\":\"此处填写{yyyy-MM-dd HH:mm:ss}格式的时间\",\"default\":\"\"}}}', 'second_hand_house/banner', 'released', '', '', NULL, '2018-05-25 17:21:07', NULL, '2018-07-11 10:08:23', 5);
INSERT INTO `cms_resource_definition` VALUES (10, '新盘推荐', '{\"title\":\"新盘推荐\",\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"title\":\"楼盘名称\",\"description\":\"楼盘名称\",\"minLength\":2,\"required\":true},\"houseId\":{\"type\":\"integer\",\"title\":\"楼盘编号\",\"default\":\"\",\"required\":true},\"cityId\":{\"type\":\"integer\",\"title\":\"城市编号\",\"default\":\"\",\"required\":true},\"beginTime\":{\"type\":\"string\",\"title\":\"有效期开始时间\",\"description\":\"有效期开始时间(格式为 yyyy-MM-dd)\",\"required\":true},\"endTime\":{\"type\":\"string\",\"title\":\"有效期截止时间\",\"description\":\"有效期截止时间(格式为 yyyy-MM-dd)\",\"required\":true}}}', 'newHouseRecommend', 'released', '', '', NULL, '2018-06-20 14:05:56', NULL, '2018-07-11 10:08:32', 4);
INSERT INTO `cms_resource_definition` VALUES (12, '首页广告', '{\"title\":\"首页广告\",\"type\":\"object\",\"properties\":{\"title\":{\"type\":\"string\",\"title\":\"标题\",\"description\":\"此处填写广告标题\",\"default\":\"\"},\"url\":{\"type\":\"string\",\"title\":\"链接地址\",\"default\":\"\"},\"h5Url\":{\"type\":\"string\",\"title\":\"h5链接地址\",\"default\":\"\"},\"imgUrl\":{\"type\":\"img\",\"title\":\"广告图片\",\"default\":\"\"},\"type\":{\"type\":\"string\",\"title\":\"广告类型\",\"enum\":[\"图文混排\",\"全图模式\"]},\"beginTime\":{\"type\":\"string\",\"title\":\"开始时间\",\"description\":\"此处必须填写{2018-06-01 00:00:00}格式的时间\",\"default\":\"\"},\"endTime\":{\"type\":\"string\",\"title\":\"结束时间\",\"description\":\"此处必须填写{2018-06-02 23:59:59}格式的时间\",\"default\":\"\"}}}', 'home/advertise', 'released', '', '', NULL, '2018-08-16 09:55:42', NULL, '2018-08-17 17:09:15', 11);
INSERT INTO `cms_resource_definition` VALUES (13, '小区广告', '{\"title\":\"小区广告\",\"type\":\"object\",\"properties\":{\"clickUrl\":{\"type\":\"string\",\"title\":\"链接地址\",\"default\":\"\"},\"h5Url\":{\"type\":\"string\",\"title\":\"h5链接地址\",\"default\":\"\"},\"imgUrl\":{\"type\":\"img\",\"title\":\"广告图片\",\"default\":\"\"},\"plateId\":{\"type\":\"integer\",\"title\":\"板块id\",\"description\":\"此处应填写板块id，全国、城市级别的广告，此项不填默认0\",\"default\":\"\"},\"houseId\":{\"type\":\"integer\",\"title\":\"小区id\",\"description\":\"此处应填写小区id，全国、城市、版块级别的广告，此项不填默认0\",\"default\":\"\"},\"type\":{\"type\":\"string\",\"title\":\"广告类型\",\"description\":\"选择广告的类型\",\"enum\":[\"小区--看房笔记广告\",\"房源详情页广告\",\"小区详情页--挂牌行情广告\",\"小区详情页--历史成交广告\",\"指定城市的广告\",\"估价详情页的广告\",\"所有城市广告\",\"地产头条--推荐模块广告\",\"地产头条--问答模块广告\",\"板块详情页--行情参考广告\",\"板块详情页--板块生活广告\",\"发现栏目广告\",\"文章详情页广告 \"]},\"status\":{\"type\":\"integer\",\"title\":\"广告状态\",\"description\":\" 1：正常有效 ;  2：无效\",\"enum\":[1,2]},\"remark\":{\"type\":\"string\",\"title\":\"备注\",\"description\":\"中信银行贷款时需要\",\"default\":\"\"},\"beginTime\":{\"type\":\"string\",\"title\":\"开始时间\",\"description\":\"此处必须填写{2018-06-01 00:00:00}格式的时间\",\"default\":\"\"},\"endTime\":{\"type\":\"string\",\"title\":\"结束时间\",\"description\":\"此处必须填写{2018-06-02 23:59:59}格式的时间\",\"default\":\"\"}}}', 'house/advertise', 'released', '', '', NULL, '2018-08-16 09:56:13', NULL, '2018-08-22 14:13:22', 14);
INSERT INTO `cms_resource_definition` VALUES (14, '会员卡试用', '{\r\n	\"title\": \"免费查看专家版\",\r\n	\"type\": \"object\",\r\n	\"properties\": {\r\n		\"houseId\": {\r\n			\"type\": \"string\",\r\n			\"title\": \"小区id\",\r\n			\"default\": \"\"\r\n		},\"houseName\": {\r\n			\"type\": \"string\",\r\n			\"title\": \"小区名称\",\r\n			\"default\": \"\"\r\n		},\r\n		\"beginTime\": {\r\n			\"type\": \"string\",\r\n			\"title\": \"开始时间\",\r\n			\"description\": \"此处填写{yyyy-MM-dd HH:mm:ss}格式的时间\",\r\n			\"default\": \"\"\r\n		},\r\n		\"endTime\": {\r\n			\"type\": \"string\",\r\n			\"title\": \"结束时间\",\r\n			\"description\": \"此处填写{yyyy-MM-dd HH:mm:ss}格式的时间\",\r\n			\"default\": \"\"\r\n		}\r\n	}\r\n}', 'member/try', 'released', '', '', NULL, '2018-08-16 17:01:17', NULL, '2018-08-16 17:01:22', 1);
INSERT INTO `cms_resource_definition` VALUES (15, '城市详情页广告', '{\"title\":\"城市详情页广告\",\"type\":\"object\",\"properties\":{\"nativeUrl\":{\"type\":\"string\",\"title\":\"链接地址\",\"default\":\"rabbit://buyCard\"},\"h5Url\":{\"type\":\"string\",\"title\":\"h5链接地址\",\"default\":\"\"},\"imgUrl\":{\"type\":\"img\",\"title\":\"广告图片\",\"default\":\"\"},\"status\":{\"type\":\"string\",\"title\":\"广告状态\",\"enum\":[\"有效\",\"无效\"]},\"beginTime\":{\"type\":\"string\",\"title\":\"开始时间\",\"description\":\"此处必须填写{2018-06-01 00:00:00}格式的时间\",\"default\":\"\"},\"endTime\":{\"type\":\"string\",\"title\":\"结束时间\",\"description\":\"此处必须填写{2018-06-02 23:59:59}格式的时间\",\"default\":\"\"}}}', 'city_detail/advertise', 'released', '', '', NULL, '2018-08-21 17:50:03', NULL, '2018-08-22 14:05:28', 3);
INSERT INTO `cms_resource_definition` VALUES (16, '品牌logo', '{\"title\":\"品牌LOGO\",\"type\":\"object\",\"properties\":{\"agentName\":{\"type\":\"string\",\"title\":\"地产品牌名\",\"enum\":[\"21世纪网\",\"中原\",\"搜房网\"],\"default\":\"\"},\"top_logo1\":{\"type\":\"string\",\"title\":\"top_logo1\",\"default\":\"\",\"description\":\"头部logo1的链接\"},\"bottom_logo1\":{\"type\":\"string\",\"title\":\"bottom_logo1\",\"description\":\"底部logo1的链接\",\"default\":\"\"},\"top_logo2\":{\"type\":\"string\",\"title\":\"top_logo2\",\"description\":\"头部logo2的链接\",\"default\":\"\"},\"bottom_logo2\":{\"type\":\"string\",\"title\":\"bottom_logo2\",\"description\":\"底部logo2的链接\",\"default\":\"\"},\"tag_logo\":{\"type\":\"string\",\"title\":\"tag_logo\",\"default\":\"\"}}}', 'brand/logo', 'released', '', '', NULL, '2018-08-23 17:11:45', NULL, '2018-08-23 19:33:26', 5);

SET FOREIGN_KEY_CHECKS = 1;
